# Generated by Django 3.1.13 on 2023-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errors',
            name='o_message',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errors',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
